version: 2

models:
  - name: stg_invoices
    description: Staged data invoices from CFE
    columns:
      - name: invoice_id
        description: The primary key for invoices
        tests:
          - unique
          - not_null
          
        